#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate the Python Learn course files."""
import json, os, sys

os.chdir(os.path.dirname(os.path.abspath(__file__)))

# Generate course.json using Python dict (avoids quote issues)
course = {}

def add_lesson(lid, title, ltype="", part=0, exercises=None, project_code=""):
    if exercises is None: exercises = []
    lesson = {"title": title, "exercises": []}
    for q, a, h in exercises:
        lesson["exercises"].append({"question": q, "answer": a, "hint": h})
    if ltype: lesson["type"] = ltype
    if part > 0: lesson["project_part"] = part
    if project_code: lesson["project_code"] = project_code
    course[str(lid)] = lesson

# Add ALL lessons from all sections
# Section 1: Variables, Booleans, Strings, Input
add_lesson(1,"Creating variables","",0,[("Create a variable 'name' with your name and print it",'name = "Ana"\nprint(name)','Use assignment and print()')])
add_lesson(2,"Using variables","",0,[("Create a=5 and b=3, print sum and difference",'a = 5\nb = 3\nprint(a + b)\nprint(a - b)','Assign then use + and -')])
add_lesson(3,"True and False","",0,[("Create a boolean 'is_raining' and print it",'is_raining = True\nprint(is_raining)','Use True or False')])
add_lesson(4,"Equality and verification","",0,[("Check if 10 equals 10",'print(10 == 10)','Use == for equality')])
add_lesson(5,"Format strings","",0,[("Create fruit variable, print 'I love <fruit>'",'fruit = "apple"\nprint(f"I love {fruit}")','Use f-string')])
add_lesson(6,"Python basics","PRACTICE",0,[("Create name, age, city and print formatted",'name = "Ana"\nage = 25\ncity = "Lima"\nprint(f"I am {name}, {age} from {city}")','Use f-strings')])
add_lesson(7,"Bot - Part 1","PROJECT_GUIDED",1,[("Build a bot that greets the user",'name = input("What is your name? ")\nprint(f"Hello, {name}! Nice to meet you!")\nprint("I am your Python bot. How can I help?")','Use input() and f-string')],"print('Bot: Hello!')\nname = input('Bot: What is your name? ')\nprint(f'Bot: Nice to meet you, {name}!')\nprint('I am your Python bot. How can I help?')\n")
add_lesson(8,"Comparing numbers","",0,[("Check if number is positive, negative, or zero",'num = int(input("Num: "))\nif num > 0:\n    print("Positive")\nelif num < 0:\n    print("Negative")\nelse:\n    print("Zero")','Use if/elif/else')])
add_lesson(9,"Comparing strings","",0,[("Ask for name, check if 'Ana'",'name = input("Your name: ")\nif name.lower() == "ana":\n    print("Hello Ana!")\nelse:\n    print(f"Hello {name}!")','Use .lower()')])
add_lesson(10,"Discovering types","",0,[("Create vars of each type and print types",'x=10; y="hello"; z=3.14; w=True\nprint(type(x)); print(type(y)); print(type(z)); print(type(w))','Use type() function')])
add_lesson(11,"Types and comparisons","PRACTICE",0,[("Ask two numbers, convert, print larger",'a = int(input("First: ")); b = int(input("Second: "))\nif a > b: print(f"{a} larger")\nelif b > a: print(f"{b} larger")\nelse: print("Equal")','Use int() to convert')])
add_lesson(12,"Input","",0,[("Ask name and age, print greeting",'name = input("Your name: ")\nage = int(input("Your age: "))\nprint(f"Hello {name}! You are {age}."','Use input() and f-string')])
add_lesson(13,"Bot - Part 2","PROJECT_GUIDED",2,[("Build interactive bot conversation",'print("Bot: Hello!")\nname = input("Bot: What is your name? ")\nprint(f"Bot: Nice to meet you, {name}!")\nmood = input("Bot: How are you? ")\nif mood.lower() == "good":\n    print("Bot: Great!")\nelse:\n    print("Bot: Hope you feel better!")\nprint(f"Bot: Goodbye {name}!")','Use input() and if/else')],"print('Bot: Hello!')\nname = input('Bot: What is your name? ')\nprint(f'Bot: Nice to meet you, {name}!')\nmood = input('Bot: How are you? ')\nif mood.lower() == 'good':\n    print('Bot: Great!')\nelse:\n    print('Bot: Hope you feel better!')\nprint(f'Bot: Goodbye {name}!')\n")

# Section 2: Conditionals, Loops, RPS
add_lesson(14,"Decision making","",0,[("Check if number is even or odd",'num = int(input("Num: "))\nif num % 2 == 0:\n    print("Even")\nelse:\n    print("Odd")','Use % modulo')])
add_lesson(15,"Using conditions","",0,[("Check multiple criteria",'age = int(input("Age: "))\nif age >= 18 and age < 65:\n    print("Working adult")\nelif age >= 65:\n    print("Senior")\nelse:\n    print("Minor")','Use and/or')])
add_lesson(16,"Conditional statements 1","PRACTICE",0,[("Write access level checker",'level = input("Level (admin/user): ")\nif level.lower() == "admin":\n    print("Full access")\nelse:\n    print("Limited access")','Use if/else with strings')])
add_lesson(17,"Coding Else statements","",0,[("Create calculator with if/elif/else",'op = input("Op (+,-,*,/): ")\na = float(input("A: ")); b = float(input("B: "))\nif op == "+": print(a+b)\nelif op == "-": print(a-b)\nelif op == "*": print(a*b)\nelse: print(a/b)','Chain if/elif/else')])
add_lesson(18,"Adding Elif","",0,[("Create grading system",'score = int(input("Score: "))\nif score >= 90: print("A")\nelif score >= 80: print("B")\nelif score >= 70: print("C")\nelse: print("F")','Use elif for ranges')])
add_lesson(19,"Using complex decisions","",0,[("Combine and/or/not",'temp = int(input("Temp: ")); rain = input("Rain? (yes/no): ")\nif temp > 30 and rain.lower() != "yes":\n    print("Hot and sunny!")\nelif temp < 10 or rain.lower() == "yes":\n    print("Cold or rainy")\nelse:\n    print("Pleasant")','Combine and/or/not')])
add_lesson(20,"Conditional statements 2","PRACTICE",0,[("Create login checker",'user = input("Username: "); p = input("Password: ")\nif user == "admin" and p == "1234":\n    print("Access granted")\nelse:\n    print("Access denied")','Combine checks')])
add_lesson(21,"Rock Paper Scissors - Part 1","PROJECT_GUIDED",1,[("Build RPS game logic",'import random\noptions = ["rock","paper","scissors"]\npc = random.choice(options)\nyou = input("rock/paper/scissors: ")\nprint(f"PC: {pc}")\nif you == pc: print("Tie!")\nelif (you=="rock" and pc=="scissors") or (you=="paper" and pc=="rock") or (you=="scissors" and pc=="paper"):\n    print("You win!")\nelse: print("PC wins!")','Use random.choice() and if/elif')],"import random\noptions = ['rock','paper','scissors']\npc = random.choice(options)\nyou = input('rock/paper/scissors: ')\nprint(f'PC: {pc}')\nif you == pc: print('Tie!')\nelif (you=='rock' and pc=='scissors') or (you=='paper' and pc=='rock') or (you=='scissors' and pc=='paper'):\n    print('You win!')\nelse: print('PC wins!')\n")
add_lesson(22,"Auto-assignment and operators","",0,[("Use +=, -=, *=",'x = 10\nx += 5\nx -= 3\nx *= 2\nprint(x)','Use += -= *= operators')])
add_lesson(23,"While loops","",0,[("Count from 1 to 5",'i = 1\nwhile i <= 5:\n    print(i)\n    i += 1','Use while with counter')])
add_lesson(24,"Stopping while loops","",0,[("Use break to stop early",'while True:\n    cmd = input("Enter (quit to stop): ")\n    if cmd == "quit": break\n    print(f"You said: {cmd}")\nprint("Loop stopped!")','Use break statement')])
add_lesson(25,"Loops 1","PRACTICE",0,[("Sum 1 to 10 using while",'s = 0; i = 1\nwhile i <= 10:\n    s += i; i += 1\nprint(f"Sum: {s}")','Use while and +=')])
add_lesson(26,"While loop control","",0,[("Use continue and break",'i = 0\nwhile i < 10:\n    i += 1\n    if i % 2 == 0: continue\n    if i > 7: break\n    print(i)','Use continue and break')])
add_lesson(27,"For loops","",0,[("Iterate over a list",'fruits = ["apple","banana","cherry"]\nfor f in fruits:\n    print(f)','Use for to iterate')])
add_lesson(28,"Loops 2","PRACTICE",0,[("Find max in a list",'nums = [3,7,2,9,1]\nmax_val = nums[0]\nfor n in nums:\n    if n > max_val: max_val = n\nprint(f"Max: {max_val}")','Use for loop with if')])
add_lesson(29,"Advanced loop control","",0,[("Use else clause with loops",'for i in range(5):\n    if i == 3: break\n    print(i)\nelse:\n    print("Completed!")\nprint("Done!")','Use loop else clause')])
add_lesson(30,"Loops 3","PRACTICE",0,[("Multiplication table",'for i in range(1, 6):\n    for j in range(1, 6):\n        print(f"{i*j:4}", end="")\n    print()','Use nested for loops')])
add_lesson(31,"Rock Paper Scissors - Part 2","PROJECT_GUIDED",2,[("Play best of 3",'import random\noptions = ["rock","paper","scissors"]\nscore = 0\nfor _ in range(3):\n    pc = random.choice(options)\n    you = input("rock/paper/scissors: ")\n    if you == pc: print("Tie!")\n    elif (you=="rock" and pc=="scissors") or (you=="paper" and pc=="rock") or (you=="scissors" and pc=="paper"):\n        score += 1; print("You win!")\n    else: print("PC wins!")\nprint(f"Final: {score}/3")','Use for loop for 3 rounds')],"import random\noptions = ['rock','paper','scissors']\nscore = 0\nfor _ in range(3):\n    pc = random.choice(options)\n    you = input('rock/paper/scissors: ')\n    if you == pc: print('Tie!')\n    elif (you=='rock' and pc=='scissors') or (you=='paper' and pc=='rock') or (you=='scissors' and pc=='paper'):\n        score += 1; print('You win!')\n    else: print('PC wins!')\nprint(f'Final: {score}/3')\n")

# Section 3: Lists
add_lesson(32,"Grouping data in lists","",0,[("Create a list of 5 favorite foods",'foods = ["pizza","sushi","tacos","pasta","burger"]\nprint(foods)','Create a list with []')])
add_lesson(33,"Changing data in lists","",0,[("Change an element",'fruits = ["apple","banana","cherry"]\nfruits[1] = "blueberry"\nprint(fruits)','Use index assignment')])
add_lesson(34,"Updating lists","",0,[("Add and remove elements",'fruits = ["apple","banana"]\nfruits.append("cherry")\nfruits.insert(1, "mango")\nfruits.remove("banana")\nprint(fruits)','Use append/insert/remove')])
add_lesson(35,"Organizing data 1","PRACTICE",0,[("Sort a list",'nums = [5,2,8,1,9]\nnums.sort()\nprint(nums)','Use .sort()')])
add_lesson(36,"Looping over lists","",0,[("Process list elements",'numbers = [10,20,30,40,50]\nfor n in numbers:\n    print(n * 2)','Use for to iterate')])
add_lesson(37,"Deciding with lists","",0,[("Check if item exists",'fruits = ["apple","banana","cherry"]\nitem = input("Search: ")\nif item in fruits:\n    print(f"{item} found!")\nelse:\n    print(f"{item} not found")','Use "in" operator')])
add_lesson(38,"Organizing data 2","PRACTICE",0,[("Reverse and sort",'nums = [3,1,4,1,5,9]\nnums.reverse()\nnums.sort()\nprint(nums)','Use .reverse() and .sort()')])
add_lesson(39,"To-Do List - Part 1","PROJECT_GUIDED",1,[("Create a basic to-do list",'tasks = []\nwhile True:\n    task = input("Add task (or quit): ")\n    if task == "quit": break\n    tasks.append(task)\n    print(f"Task added: {task}")\nprint(f"Total: {len(tasks)}")','Use list and while')],"tasks = []\nwhile True:\n    task = input('Add task (or quit): ')\n    if task == 'quit': break\n    tasks.append(task)\n    print(f'Task added: {task}')\nprint(f'Total: {len(tasks)}')\n")
add_lesson(40,"Finding extreme data","",0,[("Find max, min, average",'nums = [10,5,8,3,12]\nprint(f"Max: {max(nums)}")\nprint(f"Min: {min(nums)}")\nprint(f"Avg: {sum(nums)/len(nums):.2f}")','Use max/min/sum/len')])
add_lesson(41,"Sorting data","",0,[("Sort in different ways",'names = ["Carlos","Ana","Bob"]\nnames.sort()\nprint(names)\nnames.sort(reverse=True)\nprint(names)','Use .sort() with reverse')])
add_lesson(42,"Using Lists 1","PRACTICE",0,[("Grocery list analysis",'grocery = ["milk","eggs","bread","milk","cheese"]\nprint(f"Total: {len(grocery)}")\nprint(f"Unique: {len(set(grocery))}")','Use len(), count(), set()')])
add_lesson(43,"Adding list elements","",0,[("Combine lists",'list1 = [1,2,3]\nlist2 = [4,5,6]\nlist1.extend(list2)\nprint(list1)','Use extend() or +')])
add_lesson(44,"Counting elements","",0,[("Count occurrences",'colors = ["red","blue","red","green","red"]\nprint(f"Red: {colors.count(\'red\')}")','Use .count() method')])
add_lesson(45,"Using Lists 2","PRACTICE",0,[("Filter and transform",'nums = [1,2,3,4,5]\nevens = [n for n in nums if n % 2 == 0]\nprint(f"Evens: {evens}")','Use list comprehension')])
add_lesson(46,"To-Do List - Part 2","PROJECT_GUIDED",2,[("Add menu and delete tasks",'tasks = []\nwhile True:\n    print("\\n1.Add 2.Remove 3.Show 4.Quit")\n    cmd = input("Choose: ")\n    if cmd == "1": tasks.append(input("Task: "))\n    elif cmd == "2":\n        if tasks: tasks.pop(int(input("Num: "))-1)\n    elif cmd == "3": print(tasks)\n    elif cmd == "4": break','Use while with menu')],"tasks = []\nwhile True:\n    print('\\n1.Add 2.Remove 3.Show 4.Quit')\n    cmd = input('Choose: ')\n    if cmd == '1': tasks.append(input('Task: '))\n    elif cmd == '2':\n        if tasks: tasks.pop(int(input('Num: '))-1)\n    elif cmd == '3': print(tasks)\n    elif cmd == '4': break\n")

# Section 4: Functions
add_lesson(47,"Reusing code with functions","",0,[("Create a greet function",'def greet(name):\n    return f"Hello, {name}!"\nprint(greet("Ana"))','Use def and return')])
add_lesson(48,"Creating parameters","",0,[("Create function with parameters",'def add(a, b):\n    return a + b\nprint(add(3, 5))','Define parameters')])
add_lesson(49,"Return values","",0,[("Return multiple values",'def stats(nums):\n    return max(nums), min(nums), sum(nums)/len(nums)\nm, n, avg = stats([1,2,3,4,5])','Use return with multiple values')])
add_lesson(50,"Using multiple parameters","",0,[("Function with many parameters",'def describe(name, age, city):\n    return f"{name} is {age}, lives in {city}"\nprint(describe("Ana", 25, "Lima"))','Use multiple parameters')])
add_lesson(51,"Understanding functions","",0,[("Understand scope",'x = 10\ndef show():\n    x = 5\n    print(f"Inside: {x}")\nshow()\nprint(f"Outside: {x}")','Local vs global scope')])
add_lesson(52,"Functions 1","PRACTICE",0,[("Check if string is palindrome",'def is_palindrome(s):\n    return s == s[::-1]\nprint(is_palindrome("radar"))','Use slicing')])
add_lesson(53,"Food Ordering System - Part 1","PROJECT_GUIDED",1,[("Build Italian food ordering",'menu = {"pizza": 10, "pasta": 8, "salad": 5}\nprint("Menu:")\nfor item, price in menu.items():\n    print(f"  {item}: ${price}")\norder = input("What would you like? ")\nif order in menu:\n    print(f"Your {order} costs ${menu[order]}")\nelse:\n    print("Not on menu")','Use dict and for loop')],"menu = {'pizza': 10, 'pasta': 8, 'salad': 5}\nprint('Menu:')\nfor item, price in menu.items():\n    print(f'  {item}: ${price}')\norder = input('What would you like? ')\nif order in menu:\n    print(f'Your {order} costs ${menu[order]}')\nelse:\n    print('Not on menu')\n")
add_lesson(54,"Functions and variable scope","",0,[("Use global keyword",'count = 0\ndef increment():\n    global count\n    count += 1\nincrement()\nprint(count)','Use global keyword')])
add_lesson(55,"Deciding with functions","",0,[("If/else inside functions",'def access_level(age):\n    if age >= 18: return "Adult"\n    elif age >= 13: return "Teen"\n    else: return "Child"\nprint(access_level(25))','Return from function')])
add_lesson(56,"Functions with lists","",0,[("Process list in function",'def double_all(nums):\n    return [n * 2 for n in nums]\nprint(double_all([1,2,3]))','Use list comprehension in function')])
add_lesson(57,"Functions with loops","",0,[("Use loops inside functions",'def countdown(n):\n    while n > 0:\n        print(n)\n        n -= 1\ncountdown(5)','Use while in function')])
add_lesson(58,"Functions 2","PRACTICE",0,[("Calculate factorial",'def factorial(n):\n    result = 1\n    for i in range(1, n+1):\n        result *= i\n    return result\nprint(factorial(5))','Use loop in function')])
add_lesson(59,"Food Ordering System - Part 2","PROJECT_GUIDED",2,[("Add diverse cuisines",'cuisines = {"italian": {"pizza": 10, "pasta": 8}, "mexican": {"taco": 5, "burrito": 8}, "japanese": {"sushi": 12, "ramen": 9}}\nfor cuisine, items in cuisines.items():\n    print(f"{cuisine.title()}:")\n    for item, price in items.items():\n        print(f"  {item}: ${price}")\nprint(f"Total: {len(cuisines)} cuisines")','Nested dicts and loops')],"cuisines = {'italian': {'pizza': 10, 'pasta': 8}, 'mexican': {'taco': 5, 'burrito': 8}, 'japanese': {'sushi': 12, 'ramen': 9}}\nfor cuisine, items in cuisines.items():\n    print(f'\\n{cuisine.title()}:')\n    for item, price in items.items():\n        print(f'  {item}: ${price}')\nprint(f'Total cuisines: {len(cuisines)}')\n")

# Section 5: Tuples, Dicts, Sets
add_lesson(60,"Creating tuples","",0,[("Create tuples",'point = (3, 4)\ncolors = ("red", "blue", "green")\nprint(point[0])','Use () to create tuple')])
add_lesson(61,"Tuples and lists","",0,[("Convert between tuples and lists",'t = (1, 2, 3)\nl = list(t)\nl.append(4)\nt2 = tuple(l)\nprint(t2)','Use list() and tuple()')])
add_lesson(62,"Returning tuples","",0,[("Return multiple values as tuple",'def get_min_max(nums):\n    return min(nums), max(nums)\nlo, hi = get_min_max([3,1,4,1,5])','Use tuple unpacking')])
add_lesson(63,"Creating dictionaries","",0,[("Create and access dicts",'person = {"name": "Ana", "age": 25}\nprint(person["name"])\nperson["city"] = "Lima"\nprint(person)','Use {} and [] access')])
add_lesson(64,"Using dictionaries","",0,[("Iterate over dicts",'student = {"name": "Ana", "grade": 90}\nfor key, val in student.items():\n    print(f"{key}: {val}")\nprint(f"Keys: {list(student.keys())}")','Use .items(), .keys()')])
add_lesson(65,"Tuples, dicts, sets 1","PRACTICE",0,[("Use all three structures",'scores = {"Ana": 90, "Bob": 85}\nsorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)\nprint(sorted_scores)\nunique_grades = set(scores.values())\nprint(unique_grades)','Combine dict, tuple, set')])
add_lesson(66,"Draw a Card - Part 1","PROJECT_GUIDED",1,[("Create virtual deck and draw cards",'import random\nsuits = ["Hearts", "Diamonds", "Clubs", "Spades"]\nranks = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"]\ndeck = [(r, s) for s in suits for r in ranks]\nrandom.shuffle(deck)\nprint(f"Deck has {len(deck)} cards")\ncard = deck.pop()\nprint(f"You drew: {card[0]} of {card[1]}")','Use list comprehension and random')],"import random\nsuits = ['Hearts', 'Diamonds', 'Clubs', 'Spades']\nranks = ['A','2','3','4','5','6','7','8','9','10','J','Q','K']\ndeck = [(r,s) for s in suits for r in ranks]\nrandom.shuffle(deck)\nprint(f'Deck has {len(deck)} cards')\ncard = deck.pop()\nprint(f'You drew: {card[0]} of {card[1]}')\n")
add_lesson(67,"Creating sets","",0,[("Create and use sets",'colors = {"red", "blue", "green"}\ncolors.add("yellow")\ncolors.discard("blue")\nprint(colors)','Use {} for set')])
add_lesson(68,"Using sets","",0,[("Set operations",'a = {1,2,3,4}\nb = {3,4,5,6}\nprint(f"Union: {a | b}")\nprint(f"Intersection: {a & b}")\nprint(f"Difference: {a - b}")','Use | & - operators')])
add_lesson(69,"Sets and lists","",0,[("Convert between sets and lists",'nums = [1,2,2,3,3,4]\nunique = list(set(nums))\nprint(unique)','Use set() for dedup')])
add_lesson(70,"Set operations","",0,[("Use set operations for data",'math = {"Ana", "Bob", "Carlos"}\nsci = {"Bob", "Carlos", "Diana"}\nprint(f"Both: {math & sci}")\nprint(f"Only math: {math - sci}")','Use set operations')])
add_lesson(71,"Draw a Card - Part 2","PROJECT_GUIDED",2,[("Play card game with multiple draws",'import random\nsuits = ["Hearts","Diamonds","Clubs","Spades"]\nranks = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"]\nvalues = {str(i): i for i in range(2,11)}; values.update({"A":11,"J":10,"Q":10,"K":10})\ndeck = [(r,s) for s in suits for r in ranks]\nrandom.shuffle(deck)\ntotal = 0\nfor _ in range(2):\n    card = deck.pop()\n    total += values[card[0]]\n    print(f"Drew {card[0]} of {card[1]} -> Total: {total}")\nprint(f"Final total: {total}")','Use for loop and dict lookup')],"import random\nsuits = ['Hearts','Diamonds','Clubs','Spades']\nranks = ['A','2','3','4','5','6','7','8','9','10','J','Q','K']\nvalues = {str(i): i for i in range(2,11)}; values.update({'A':11,'J':10,'Q':10,'K':10})\ndeck = [(r,s) for s in suits for r in ranks]\nrandom.shuffle(deck)\ntotal = 0\nfor _ in range(2):\n    card = deck.pop()\n    total += values[card[0]]\n    print(f'Drew {card[0]} of {card[1]} -> Total: {total}')\nprint(f'Final total: {total}')\n")

# Section 6: Modules and Dependencies
add_lesson(72,"Modules","",0,[("Import and use a module",'import random\nprint(random.randint(1, 100))','Use import statement')])
add_lesson(73,"Modules","PRACTICE",0,[("Import specific functions",'from math import sqrt, pi\nprint(sqrt(16))\nprint(pi)','Use from...import')])
add_lesson(74,"Creating your own modules","",0,[("Create and import custom module",'# In mymodule.py: def greet(name): return f"Hello {name}!"\n# In main.py: from mymodule import greet\n# print(greet("World"))','Create separate .py file')])
add_lesson(75,"Organizing multi-file programs","",0,[("Split code into multiple files",'# config.py: API_KEY = "abc"\n# main.py: from config import API_KEY\n# print(API_KEY)','Use import across files')])
add_lesson(76,"Understanding Python packages","",0,[("Understand package structure",'# mypackage/__init__.py\n# mypackage/utils.py\n# from mypackage.utils import helper','Understand __init__.py')])
add_lesson(77,"Python modules","PRACTICE",0,[("Use os and sys modules",'import os, sys\nprint(os.getcwd())\nprint(sys.version)','Import os and sys')])
add_lesson(78,"Installing third-party packages","",0,[("Install and use pip packages",'# pip install requests\nimport requests\n# response = requests.get("https://api.example.com")','Use pip to install')])
add_lesson(79,"Managing package versions","",0,[("Check and manage versions",'import requests\nprint(requests.__version__)','Use __version__')])
add_lesson(80,"Python dependencies","PRACTICE",0,[("Create a requirements.txt",'# pip freeze > requirements.txt\n# pip install -r requirements.txt','Use pip freeze and install')])
add_lesson(81,"Damage Calculator - Part 1","PROJECT_GUIDED",1,[("Create damage calculator",'import random, math\nattack = random.randint(10, 50)\ndefense = random.randint(5, 25)\ndamage = max(0, attack - defense + math.floor(random.gauss(0, 5)))\nprint(f"Attack: {attack}, Defense: {defense}, Damage: {damage}")','Use random, math modules')],"import random, math\nattack = random.randint(10, 50)\ndefense = random.randint(5, 25)\ndamage = max(0, attack - defense + math.floor(random.gauss(0, 5)))\nprint(f'Attack: {attack}, Defense: {defense}, Damage: {damage}')\n")

# Section 7: Errors and Exception Handling
add_lesson(82,"Errors and exceptions","",0,[("Handle exceptions with try/except",'try:\n    x = int(input("Num: "))\n    print(f"You entered {x}")\nexcept ValueError:\n    print("That was not a number!")','Use try/except')])
add_lesson(83,"Raising exceptions","",0,[("Raise your own exceptions",'def divide(a, b):\n    if b == 0: raise ValueError("Cannot divide by zero")\n    return a / b\ntry:\n    print(divide(10, 0))\nexcept ValueError as e:\n    print(f"Error: {e}")','Use raise keyword')])
add_lesson(84,"Errors and exceptions","PRACTICE",0,[("Create robust division function",'def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None\n    except TypeError:\n        return "Invalid input"\nprint(safe_divide(10, 2))\nprint(safe_divide(10, 0))','Use multiple except blocks')])
add_lesson(85,"Handling multiple exception types","",0,[("Handle different exception types",'try:\n    f = open("file.txt")\n    data = f.read()\n    num = int(data)\nexcept FileNotFoundError:\n    print("File not found")\nexcept ValueError:\n    print("Not a valid number")\nfinally:\n    print("Cleanup done")','Multiple except blocks')])
add_lesson(86,"Working with exception messages","",0,[("Create custom exception messages",'class NegativeError(Exception):\n    pass\ndef process(n):\n    if n < 0: raise NegativeError(f"{n} is negative!")\ntry:\n    process(-5)\nexcept NegativeError as e:\n    print(f"Custom error: {e}")','Define custom exception class')])
add_lesson(87,"Exception handling","PRACTICE",0,[("Create file reader with error handling",'def read_number(filename):\n    try:\n        with open(filename) as f:\n            return float(f.read().strip())\n    except FileNotFoundError:\n        print("File missing")\n    except ValueError:\n        print("Not a number")\n    return None\nprint(read_number("data.txt"))','Use try/except/finally with files')])
add_lesson(88,"Best practices in exception handling","",0,[("Follow best practices",'# Be specific with exception types\n# Never use bare except:\n# Use finally for cleanup','Best practice patterns')])
add_lesson(89,"Exceptions","PRACTICE",0,[("Create a robust calculator",'def calc(a, b, op):\n    try:\n        a, b = float(a), float(b)\n        if op == "+": return a+b\n        elif op == "-": return a-b\n        elif op == "*": return a*b\n        elif op == "/":\n            if b==0: raise ZeroDivisionError\n            return a/b\n        else: raise ValueError(f"Unknown op: {op}")\n    except (ValueError, ZeroDivisionError) as e:\n        return f"Error: {e}"\nprint(calc(10, 5, "+"))\nprint(calc(10, 0, "/"))','Combine all error handling')])
add_lesson(90,"Sensor Reading Validator - Part 1","PROJECT_GUIDED",1,[("Validate sensor readings",'import random\nclass InvalidReadingError(Exception):\n    pass\ndef read_sensor():\n    val = random.uniform(-10, 50)\n    if val < 0 or val > 40: raise InvalidReadingError(f"Invalid reading: {val}")\n    return val\nreadings = []\nfor i in range(10):\n    try:\n        r = read_sensor()\n        readings.append(r)\n        print(f"Reading {i+1}: {r:.2f}")\n    except InvalidReadingError as e: print(f"Error: {e}")\nif readings: print(f"Valid readings: {len(readings)}/10")','Use custom exceptions and loops')],"import random\nclass InvalidReadingError(Exception):\n    pass\ndef read_sensor():\n    val = random.uniform(-10, 50)\n    if val < 0 or val > 40: raise InvalidReadingError(f'Invalid reading: {val}')\n    return val\nreadings = []\nfor i in range(10):\n    try:\n        r = read_sensor()\n        readings.append(r)\n        print(f'Reading {i+1}: {r:.2f}')\n    except InvalidReadingError as e: print(f'Error: {e}')\nif readings: print(f'Valid readings: {len(readings)}/10')\n")

# Write course.json
with open('data/course.json', 'w', encoding='utf-8') as f:
    json.dump(course, f, indent=2, ensure_ascii=False)

print(f"Generated data/course.json with {len(course)} lessons!")
print(f"File size: {len(json.dumps(course))} characters")
